import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import '../scss/main.scss'
import { ReactNode } from 'react'

const satoshiRegular = localFont({
  src: './fonts/Satoshi-Regular.woff',
  variable: '--font-satoshi-regular',
})
const satoshiMedium = localFont({
  src: './fonts/Satoshi-Medium.woff',
  variable: '--font-satoshi-medium',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiRegular.className} ${satoshiMedium.className} antialiased`}>{children}</body>
    </html>
  )
}
